version: '3'

services:
  redis:
    image: "redis:7.0.11-alpine"
    command: redis-server --requirepass devpass
    volumes:
      - "./data/redis:/data"
    ports:
      - "6379:6379"
    networks:
      - web
networks:
  web:
    driver: bridge